/**
 * 「스마트홈 살인사건 — 목격자는 AI 스피커」(witness-01) 사건 데이터.
 *
 * 원문: docs/planning/witness-case.md(바이블 v3) · witness-player-script.md(대본 v3) · witness-player-sealed.md(봉인 v3).
 * 대사·증거 문구는 원문 그대로 옮겼다. 진상(범인·정답)은 이 파일의 SOLUTION 에만 있다 — 엔진·UI 코드는 범인을 하드코딩하지 않는다.
 * 원문과 다르게 한 점(디자인 확정본 반영): 핫스팟 좌표 3곳(L0.h5·L5.h2·L5.h3, 디자인 §8-3 A1), 정밀 조사 preNote(A2),
 * L5.h3 device 표시(로그 skin 'terminal', A5).
 */
import type {
  Break,
  CaseFile,
  Dialogue,
  Evidence,
  Face,
  Line,
  Location,
  Profile,
  Solution,
  Speaker,
  TestimonySet,
} from './types';

const d = (who: Speaker, text: string, face?: Face): Dialogue => (face ? { who, face, text } : { who, text });
const ME = (t: string, f?: Face) => d('ME', t, f);
const COP = (t: string, f?: Face) => d('COP', t, f);
const AI = (t: string, f?: Face) => d('AI', t, f);
const NARR = (t: string) => d('NARR', t);
const S1 = (t: string, f?: Face) => d('S1', t, f);
const S2 = (t: string, f?: Face) => d('S2', t, f);
const S3 = (t: string, f?: Face) => d('S3', t, f);
const S4 = (t: string, f?: Face) => d('S4', t, f);

// ─────────────────────────────── 인물 ───────────────────────────────

export const NAMES: Record<Speaker, string> = {
  S1: '선우강',
  S2: '백하늘',
  S3: '방미숙',
  S4: '표준혁',
  AI: '또박이',
  COP: '한결',
  ME: '나',
  NARR: '',
  DEV: '',
};

export const PROFILES: Profile[] = [
  {
    id: 'VICTIM',
    name: '백도진',
    age: 62,
    summary: ['도진랩 창업자·회장. 또박이 광고 모델.', "유행어 '또박아, 불 꺼. 오늘은 여기까지.'", '내일 10시 은퇴와 회사 매각을 발표할 예정이었다.'],
  },
  {
    id: 'S1',
    name: '선우강',
    age: 49,
    summary: ['도진랩 공동창업자·CTO. 또박이 설계자.', '회색 후드티. 비 때문에 손님방에서 묵는다.', '매각에 반대해 왔다는 소문이 있다.'],
    secretLine: "몰래 깐 '야간 학습'으로 이 집 소리를 모았다.",
  },
  {
    id: 'S2',
    name: '백하늘',
    age: 26,
    summary: ['회장의 외동딸. 웹소설 작가.', '자기 말을 소설처럼 서술하는 버릇.', '아버지와 사이가 나쁜 건 다들 안다.'],
    secretLine: '아버지 이야기를 소설로 파는 계약 통화 중이었다.',
  },
  {
    id: 'S3',
    name: '방미숙',
    age: 58,
    summary: ['입주 가사관리인 10년 차.', "집 기기는 '집사' 공용 계정으로 다룬다.", "말버릇 '아이고, 참말로'."],
    secretLine: '토요일마다 몰래 치킨을 로비에서 받았다. 10년째.',
  },
  {
    id: 'S4',
    name: '표준혁',
    age: 41,
    summary: ['회장 수행비서 7년 차. 늘 정장 차림.', '일정·계정 관리. 집사 공용 계정도 쓴다.', '시신 발견자. 22:05~22:38 외출.'],
    secretLine: '1999년 특허 발명자 표명환의 아들.',
  },
  {
    id: 'AI',
    name: '또박이',
    summary: ["도진랩 AI 스피커 3세대. 호출어 '또박아'.", '거실 선반. 윗면에 마이크 버튼, LED 링.', '카메라는 없다. 듣고, 기록하고, 대답한다.'],
  },
];

// ─────────────────────────────── 증거 18 + 갱신 3 ───────────────────────────────

export const EVIDENCE: Evidence[] = [
  {
    id: 'E01',
    name: '순경의 초동 메모',
    kind: 'doc',
    summary: '22:39 발견. 사이드테이블 옆, 모서리 충돌 사고 추정.',
    detail: ['발견자 표준혁. 불 꺼진 거실, 멈춘 청소기 옆.', '순경 의견: 어둠 속 청소기에 걸려 넘어짐.'],
    time: '22:39',
    from: { location: 'L0', hotspot: 'L0.h1' },
    missHint: '현장 바닥 근처',
    role: ['key', 'herring'],
  },
  {
    id: 'E02',
    name: '크리스탈 트로피',
    kind: 'item',
    summary: "도진랩 '올해의 혁신상'. 모서리가 살짝 이 빠졌다.",
    detail: ['진열장 맨 앞. 지문 하나 없이 혼자 반짝인다.', '다른 상패엔 먼지가 얇게 앉아 있다.'],
    from: { location: 'L0', hotspot: 'L0.h2' },
    missHint: '거실 벽 쪽',
    role: ['means'],
  },
  {
    id: 'E03',
    name: '22:20 음성 명령',
    kind: 'log',
    reliability: 'raw',
    summary: "22:20:01 주인 음성 '또박아, 불 꺼. 오늘은 여기까지.'",
    detail: ['또박이가 주인 목소리로 판정, 거실 조명을 껐다.', '기록 그대로. 진위는 확인되지 않았다.'],
    time: '22:20',
    from: { location: 'L0', hotspot: 'L0.h3' },
    missHint: '거실의 기계',
    role: ['herring'],
  },
  {
    id: 'E03a',
    name: '정정된 음성 명령',
    kind: 'log',
    reliability: 'revised',
    summary: "22:20 '주인님 목소리'는 청소기 출발음이었다.",
    detail: ['22:20:00 청소기 출발, 1초 뒤 바닥에서 난 소리.', '또박이가 그 소리를 주인으로 잘못 판정했다.', '출발음을 바꾼 사람은 아직 모른다.'],
    time: '22:20',
    from: { break: 'C11' },
    missHint: '기계가 스스로 고친 판정',
    role: ['key'],
    upgradeOf: 'E03',
  },
  {
    id: 'E03b',
    name: '위조된 음성 명령',
    kind: 'log',
    reliability: 'forged',
    summary: "22:20 '회장 목소리'는 청소기 출발음. 설정자는 표준혁.",
    detail: ['22:02 주방 태블릿에서 출발음을 회장 녹음으로.', '회장은 그 전에 이미 쓰러져 있었다.', '22:05 외출 알리바이는 이 기록에 기대 있었다.'],
    time: '22:20',
    from: { break: 'C13' },
    missHint: '누군가의 마지막 변명',
    role: ['opportunity'],
    upgradeOf: 'E03a',
  },
  {
    id: 'E04',
    name: '트로피 조각',
    kind: 'item',
    summary: '청소기 먼지통 속 크리스탈 조각. 손톱만 하다.',
    detail: ['청소기는 22:20부터 천 주변을 돌다 멈췄다.', '유리컵치고는 두껍고 각이 졌다.'],
    from: { location: 'L0', hotspot: 'L0.h5' },
    missHint: '스피커가 청소기 얘기를 한 뒤, 거실',
    role: ['means'],
  },
  {
    id: 'E05',
    name: '청소기 예약 기록',
    kind: 'log',
    reliability: 'raw',
    summary: '21:58 1회 예약(22:20 거실) 생성. 22:02 출발음 변경.',
    detail: ['기기: 주방 홈 허브 태블릿. 계정: 집사(공용).', "출발음: 기본 '띠리링' → 사용자 지정 '생신축하.wav'.", '평소 예약 없음. 오늘이 처음.'],
    time: '21:58',
    from: { location: 'L1', hotspot: 'L1.h1' },
    missHint: '주방의 기계',
    role: ['key'],
  },
  {
    id: 'E06',
    name: '서재 조명 기록',
    kind: 'log',
    reliability: 'verified',
    summary: '서재 조명 20:40 켜짐, 21:40 꺼짐, 22:52 켜짐.',
    detail: ['22:52는 순경이 켰다.', '21:40부터 22:52까지 서재는 내내 깜깜했다.'],
    time: '21:40',
    from: { location: 'L2', hotspot: 'L2.h1' },
    missHint: '서재의 벽',
    role: ['key'],
  },
  {
    id: 'E07',
    name: '매각 계약서 사본',
    kind: 'doc',
    summary: "인수 조건 'CTO 선우강 해임, 특허 회사 귀속'에 빨간 줄.",
    detail: ["여백에 선우강의 글씨: '이건 사형선고다.'"],
    from: { location: 'L5', hotspot: 'L5.h1' },
    missHint: '잠긴 방의 가방',
    role: ['motive', 'herring'],
  },
  {
    id: 'E08',
    name: '유언장 수정 메모',
    kind: 'doc',
    summary: "회장 메모: '하늘 몫 → 재단. 월요일 변호사.'",
    detail: ['밑줄 두 번. 날짜는 오늘.'],
    from: { location: 'L2', hotspot: 'L2.h2' },
    missHint: '서재 책상',
    role: ['motive'],
  },
  {
    id: 'E09',
    name: '특허 출원서 사본',
    kind: 'doc',
    summary: "1999년 '음성 화자 식별 장치'. 발명자 '…명환', 출원인 백도진.",
    detail: ['파쇄기에 걸려 반쯤 갈렸다. 발명자 성은 잘려 나갔다.', '칼자국이 두 겹. 두 번 넣은 것 같다.'],
    from: { location: 'L2', hotspot: 'L2.h3' },
    missHint: '서재, 시간을 들여야 보이는 곳',
    role: ['motive'],
  },
  {
    id: 'E10',
    name: '해고 예고 통지서',
    kind: 'doc',
    summary: "'주택 매각에 따라 11월 30일 계약 종료.' 수신 방미숙.",
    detail: ['냉장고 문, 또박이 굿즈 자석 아래.'],
    from: { location: 'L1', hotspot: 'L1.h3' },
    missHint: '주방 어딘가',
    role: ['motive'],
  },
  {
    id: 'E11',
    name: '공유기 기록',
    kind: 'log',
    reliability: 'verified',
    summary: '21~23시 끊김 0회. 단 또박이 음성 업로드 21:41~21:56 0건.',
    detail: ['또박이는 내내 연결돼 있었다.', '보낼 소리가 없었을 뿐이다.'],
    time: '21:41',
    from: { location: 'L3', hotspot: 'L3.h1' },
    missHint: '다용도실 벽',
    role: ['key', 'opportunity'],
  },
  {
    id: 'E12',
    name: '월패드 출입 기록',
    kind: 'log',
    reliability: 'verified',
    summary: '옥상문·쪽문·현관의 열림 기록. 사용자 코드가 남는다.',
    detail: [
      '21:44 옥상문 열림(하늘) · 21:46 쪽문 나감(미숙)',
      '22:01 옥상문 닫힘 · 22:02 쪽문 들어옴(미숙)',
      '22:05 현관 나감(준혁) · 22:38 들어옴(준혁)',
    ],
    time: '21:44',
    from: { location: 'L3', hotspot: 'L3.h2' },
    missHint: '다용도실 벽',
    role: ['key', 'secret'],
  },
  {
    id: 'E13',
    name: '치킨 상자',
    kind: 'item',
    summary: '분리수거함 맨 밑. 아직 따뜻하다. 영수증 21:52 로비 전달.',
    detail: ["받는 분 '방**'. 요청: '조용히 로비로요.'", '주문 21:20. 뼈만 남았다.'],
    time: '21:52',
    from: { location: 'L1', hotspot: 'L1.h2' },
    missHint: '주방 구석',
    role: ['secret'],
  },
  {
    id: 'E14',
    name: '삭제 명령 기록',
    kind: 'log',
    reliability: 'raw',
    summary: "21:38 외부 기기 'KANG-NOTE' 접속, 데이터 삭제 명령.",
    detail: ['무엇을 지웠는지는 또박이도 모른다.', '3분 뒤, 15분짜리 기록 공백이 시작된다.'],
    time: '21:38',
    from: { press: 'T05.2' },
    missHint: '스피커의 두 번째 기록',
    role: ['herring'],
  },
  {
    id: 'E14b',
    name: '선우강의 관리자 키',
    kind: 'item',
    reliability: 'verified',
    summary: "'야간 학습' 삭제용 개발자 키. 또박이 상세 기록을 연다.",
    detail: ['지운 건 몰래 모은 학습 음성뿐이라고 한다.', "또박이 '관리자 기록' 열람 권한."],
    time: '21:38',
    from: { break: 'C02' },
    missHint: '누군가의 비밀',
    role: ['key'],
    upgradeOf: 'E14',
  },
  {
    id: 'E15',
    name: '생일 음성팩',
    kind: 'memo',
    summary: '작년 회장 생일, 비서가 청소기 출발음을 회장 목소리로.',
    detail: ["대사는 '또박아, 불 꺼. 오늘은 여기까지.'", '두 달 뒤 회장이 기본음으로 되돌렸다.', '파일은 태블릿에 남아 있다. (미숙 증언)'],
    from: { break: 'C03' },
    missHint: '가사관리인의 두 번째 이야기',
    role: ['key'],
  },
  {
    id: 'E16',
    name: '하늘의 목격',
    kind: 'memo',
    summary: '22:01 옥상에서 내려오다, 주방 태블릿 앞 정장 뒷모습.',
    detail: ['태블릿 불빛만 켜진 어두운 주방.', '얼굴은 못 봤다. 정장 차림이었다.'],
    time: '22:01',
    from: { break: 'C04' },
    missHint: '작가의 숨긴 통화',
    role: ['key'],
  },
  {
    id: 'E17',
    name: '터미널 기록',
    kind: 'log',
    reliability: 'verified',
    summary: '선우강 노트북. 21:38~22:12 입력이 한 번도 안 끊겼다.',
    detail: ["21:46 주석: '# 쿵? 회장님 또 뭐 떨어뜨리심'", "22:12 '삭제 완료'. 그 뒤 로그아웃."],
    time: '21:46',
    from: { location: 'L5', hotspot: 'L5.h3' },
    missHint: '잠긴 방, 시간을 들여야 보이는 곳',
    role: ['secret', 'key'],
  },
  {
    id: 'E18',
    name: '하늘의 이어폰',
    kind: 'item',
    summary: "옥상 천창 옆, 무선 이어폰 한 짝. 케이스에 'HANEUL'.",
    detail: ['천창 아래는 바로 거실. 지금은 블라인드.', '젖지 않았다. 캐노피 아래였다.'],
    from: { location: 'L4', hotspot: 'L4.h1' },
    missHint: '집 꼭대기',
    role: ['herring', 'secret'],
  },
];

// ─────────────────────────────── 장소 6 ───────────────────────────────

export const LOCATIONS: Location[] = [
  {
    id: 'L0',
    name: '거실 — 현장',
    art: 'living',
    initial: true,
    cost: 0,
    tutorial: true,
    look: '통유리 너머 한강, 분필 선, 멈춘 청소기, 진열장, 스피커',
    scene: '통유리 너머 비 내리는 한강. 소파와 대리석 사이드테이블, 바닥의 분필 선과 덮은 천, 그 옆에 멈춘 로봇청소기. 왼쪽 벽 진열장, 오른쪽 선반 위 스피커.',
    hotspots: [
      {
        id: 'L0.h1',
        x: 50,
        y: 62,
        label: '분필 선',
        lines: [ME('덮은 천, 대리석 사이드테이블. 모서리가 날카롭다.'), COP('제 메모예요. 어두워서 넘어진 사고 같다고 썼어요.')],
        gives: ['E01'],
      },
      {
        id: 'L0.h2',
        x: 18,
        y: 40,
        label: '트로피 진열장',
        lines: [ME("'올해의 혁신상'. 혼자만 새것처럼 반짝인다."), ME('모서리가 살짝 이가 빠졌다.')],
        gives: ['E02'],
      },
      {
        id: 'L0.h3',
        x: 82,
        y: 38,
        label: '또박이',
        device: true,
        lines: [AI('안녕하세요! 오늘 강수확률은 100%입니다.'), AI('…이미 아시겠지만요.'), ME('윗면에 마이크 버튼. 기록을 열었다.')],
        gives: ['E03'],
      },
      {
        id: 'L0.h4',
        x: 40,
        y: 75,
        label: '로봇청소기',
        device: true,
        flavor: true,
        lines: [ME("'또박이 클린'. 천 옆에서 멈춰 있다."), COP('바퀴 걸림이래요. 설정은 주방 태블릿에서 본대요.')],
      },
      {
        id: 'L0.h5',
        x: 48,
        y: 82,
        label: '청소기 먼지통',
        unlock: { flag: 'F_DUST' },
        lines: [ME('먼지 사이로 투명한 조각 하나.'), COP('유리컵… 치고는 너무 두껍죠?')],
        gives: ['E04'],
      },
    ],
  },
  {
    id: 'L1',
    name: '주방',
    art: 'kitchen',
    initial: true,
    cost: 1,
    look: '디저트 접시, 벽걸이 태블릿, 양문 냉장고, 분리수거함',
    scene: '아일랜드 식탁의 디저트 접시들, 벽걸이 태블릿, 양문 냉장고, 구석 분리수거함.',
    hotspots: [
      {
        id: 'L1.h1',
        x: 70,
        y: 30,
        label: '홈 허브 태블릿',
        device: true,
        lines: [ME("'집사(공용)' 계정. 자동 로그인 상태다."), ME('청소기 메뉴에 오늘 처음 생긴 예약이 있다.')],
        gives: ['E05'],
      },
      {
        id: 'L1.h2',
        x: 85,
        y: 78,
        label: '분리수거함',
        lines: [ME('맨 밑에 숨긴 상자. 아직 따뜻하다.'), COP('이 집 야식 금지라던데요… 치킨?')],
        gives: ['E13'],
      },
      {
        id: 'L1.h3',
        x: 20,
        y: 45,
        label: '냉장고',
        lines: [{ who: 'DEV', label: '냉장고', text: '야식은 건강에 해롭습니다. 튀김 냄새 감지.' }, ME('냉장고도 잔소리를 한다. 자석 아래 통지서.')],
        gives: ['E10'],
      },
      {
        id: 'L1.h4',
        x: 45,
        y: 65,
        label: '디저트 접시',
        flavor: true,
        lines: [ME("초콜릿 글씨 '오늘은 여기까지'. 회사 굿즈다."), COP('…하나 먹어도 돼요? 아, 증거죠.')],
      },
    ],
  },
  {
    id: 'L2',
    name: '서재',
    art: 'study',
    initial: true,
    cost: 1,
    look: '책장, 서류 책상, 조명 패널, 종이가 물린 파쇄기',
    scene: '벽 가득 책장, 서류 쌓인 원목 책상, 문 옆 조명 패널, 종이가 물린 파쇄기.',
    hotspots: [
      {
        id: 'L2.h1',
        x: 12,
        y: 40,
        label: '조명 패널',
        device: true,
        lines: [ME('스마트 조명. 켜고 끈 시각이 남는다.')],
        gives: ['E06'],
      },
      {
        id: 'L2.h2',
        x: 55,
        y: 55,
        label: '책상',
        lines: [ME('내일 발표 자료 더미. 그 위에 회장의 메모.')],
        gives: ['E08'],
      },
      {
        id: 'L2.h3',
        x: 60,
        y: 80,
        label: '파쇄기',
        precise: true,
        preNote: '종이가 물려 있다. 이어 붙이려면 시간이 든다.',
        lines: [ME('종이가 물려 멈췄다. 조각을 이어 붙인다.'), ME("1999년 특허 출원서. 발명자 칸은… '명환'."), ME('성은 칼날에 갈려 나갔다.')],
        gives: ['E09'],
      },
      {
        id: 'L2.h4',
        x: 85,
        y: 35,
        label: '책장',
        flavor: true,
        lines: [ME('자서전 『또박또박 살아라』 서른 권. 전부 새 책.'), COP('저 사인본 있어요. 중고로 샀지만.')],
      },
    ],
  },
  {
    id: 'L3',
    name: '다용도실',
    art: 'utility',
    initial: true,
    cost: 1,
    look: '세탁기, 통신 단자함, 월패드, 차단기, 쪽문',
    scene: '세탁기와 건조기, 공유기 불빛이 깜빡이는 통신 단자함, 월패드, 차단기 함, 쪽문.',
    hotspots: [
      {
        id: 'L3.h1',
        x: 25,
        y: 30,
        label: '통신 단자함',
        device: true,
        lines: [ME('공유기 관리 화면. 끊긴 적이 있는지 본다.')],
        gives: ['E11'],
      },
      {
        id: 'L3.h2',
        x: 60,
        y: 35,
        label: '월패드',
        device: true,
        lines: [ME('문마다 열린 시각과 사용자 코드가 남는다.')],
        gives: ['E12'],
      },
      {
        id: 'L3.h3',
        x: 40,
        y: 25,
        label: '차단기',
        flavor: true,
        lines: [ME('스위치 전부 ON. 여기는 무죄다.')],
      },
      {
        id: 'L3.h4',
        x: 85,
        y: 60,
        label: '쪽문',
        flavor: true,
        lines: [ME('서비스 엘리베이터로 통하는 문.'), ME('바닥에 물 한 방울. 새콤한 냄새가 난다.')],
      },
    ],
  },
  {
    id: 'L4',
    name: '옥상 정원',
    art: 'roof',
    initial: true,
    cost: 1,
    look: '캐노피 벤치, 젖은 화분, 거실 위 유리 천창',
    scene: '캐노피 아래 벤치, 젖은 화분, 거실 위 유리 천창, 멀리 깜깜한 강변도로.',
    hotspots: [
      {
        id: 'L4.h1',
        x: 50,
        y: 55,
        label: '천창',
        lines: [ME('거실 바로 위 천창. 블라인드라 안은 안 보인다.'), ME("그 옆에 이어폰 한 짝. 케이스에 'HANEUL'.")],
        gives: ['E18'],
      },
      {
        id: 'L4.h2',
        x: 20,
        y: 40,
        label: '캐노피 벤치',
        flavor: true,
        lines: [ME('벤치 한쪽만 말라 있다. 누가 오래 앉아 있었다.')],
      },
      {
        id: 'L4.h3',
        x: 80,
        y: 20,
        label: '한강 전망',
        flavor: true,
        lines: [ME('강변도로가 깜깜하다. 강력팀은 아직 멀었다.'), COP('뷰 좋네요. 아, 근무 중이죠.')],
      },
    ],
  },
  {
    id: 'L5',
    name: '손님방',
    art: 'guest',
    initial: false,
    cost: 1,
    unlock: { broken: 'C02' },
    lockedLabel: '문이 안에서 잠겨 있다. 손님 짐이 있다.',
    look: '싱글 침대, 노트북, 열린 여행 가방',
    scene: '싱글 침대 위 회색 후드티 더미, 노트북(검은 화면에 초록 글자), 열린 여행 가방.',
    hotspots: [
      {
        id: 'L5.h1',
        x: 75,
        y: 70,
        label: '여행 가방',
        lines: [ME('계약서 사본. 조항마다 빨간 줄이다.')],
        gives: ['E07'],
      },
      {
        id: 'L5.h2',
        x: 38,
        y: 44,
        label: '노트북 화면',
        flavor: true,
        lines: [ME("'purge_night.sh 완료'. 그 위로 긴 입력 기록."), ME('제대로 보려면 시간이 좀 든다.')],
      },
      {
        id: 'L5.h3',
        x: 54,
        y: 52,
        label: '노트북 입력 기록',
        device: true,
        precise: true,
        preNote: '입력 기록이 길다. 다 훑으려면 시간이 든다.',
        lines: [ME('명령어 사이에 주석 한 줄이 끼어 있다.')],
        gives: ['E17'],
      },
      {
        id: 'L5.h4',
        x: 20,
        y: 60,
        label: '후드티 더미',
        flavor: true,
        lines: [ME('같은 회색 후드티 일곱 벌. 요일별인가.'), COP('저도 근무복 일곱 벌이에요. 동질감…')],
      },
    ],
  },
];

// ─────────────────────────────── 증언 11세트 · 50줄 ───────────────────────────────

const R_VOICE = ['E05', 'E15'];

const C01: Break = {
  id: 'C01',
  tier: 'minor',
  type: 'contradiction',
  evidence: ['E01'],
  reaction: [AI('정정합니다. 저는 움직이지 않는 분은 못 느낍니다.', 'shock'), COP('기계 말도 깨지네요!'), ME('기록은 사실. 해석은 해석일 뿐이다.')],
  revisedText: '움직임은 없었습니다. 사람이 없었는지는 모릅니다.',
  unlocks: [],
  hintTopic: '움직임',
  explain: '회장은 22:39 거실 바닥에서 발견됐다. 움직이지 않았을 뿐.',
};

const C02: Break = {
  id: 'C02',
  tier: 'minor',
  type: 'contradiction',
  evidence: ['E14'],
  reaction: [
    S1("…'야간 학습'. 몰래 깐 베타 기능이에요.", 'shock'),
    S1('이 집 소리로 또박이를 가르쳤죠. 허락 없이.'),
    S1('지운 건 그 데이터뿐. 이 키로 확인해 보세요.'),
  ],
  revisedText: '몰래 모은 학습 데이터를 지웠습니다.',
  unlocks: [{ upgrade: ['E14', 'E14b'] }, { location: 'L5' }, { secret: 'S1' }],
  hintTopic: '노트북',
  explain: '21:38 그의 노트북이 이 집에서 삭제 명령을 실행했다.',
};

const C03: Break = {
  id: 'C03',
  tier: 'minor',
  type: 'contradiction',
  evidence: ['E13'],
  accept: [['E12']],
  reaction: [
    S3('아이고… 토요일마다 몰래 치킨 시켰어요. 10년.', 'shock'),
    S3('9시 46분에 나가서 10시 2분에 들어왔어요.'),
    S3('다 털렸으니 하나 더. 그 청소기, 회장님 목소리 나와요.'),
    S3('작년 생신에 비서님이 넣어 드렸지.'),
  ],
  revisedText: '9시 46분부터 10시 2분까지 로비에 다녀왔어요.',
  unlocks: [{ evidence: 'E15' }, { secret: 'S3' }, { set: 'T08' }],
  hintTopic: '야식',
  explain: '치킨은 21:52 로비에서 그녀 앞으로 전달됐다. 자고 있지 않았다.',
};

const C04: Break = {
  id: 'C04',
  tier: 'minor',
  type: 'contradiction',
  evidence: ['E12'],
  accept: [['E18']],
  reaction: [S2('…옥상에서 통화했어요. 출판사랑.', 'shock'), S2('아빠 얘기를 소설로 팔았어요. 사인까지 했고요.'), S2('내려오다 봤어요. 주방에 정장 뒷모습.')],
  revisedText: '9시 44분부터 10시 1분까지 옥상에서 통화했어요.',
  unlocks: [{ evidence: 'E16' }, { secret: 'S2' }],
  hintTopic: '옥상',
  explain: '옥상문은 21:44 하늘의 번호로 열려 22:01에 닫혔다.',
};

const C05: Break = {
  id: 'C05',
  tier: 'star',
  type: 'contradiction',
  evidence: ['E11'],
  reaction: [AI('정정합니다. 네트워크는 정상이었습니다.', 'shock'), AI('보낼 소리가 없었습니다. 마이크가 꺼져 있었습니다.'), COP('누가 일부러 껐다는 거예요?!')],
  revisedText: '15분간 마이크가 꺼져 있었습니다.',
  unlocks: [],
  hintTopic: '공백',
  explain: '공유기는 안 끊겼고 또박이 업로드만 0건. 마이크가 꺼졌다.',
};

const C06: Break = {
  id: 'C06',
  tier: 'minor',
  type: 'permission',
  evidence: ['E14b'],
  reaction: [AI('관리자 키 확인. 상세 기록을 열 수 있습니다.', 'normal'), COP('이사님 키로요? 그래도 되나…'), ME('강력팀엔 내가 설명한다.')],
  revisedText: '관리자 권한 확인. 공백의 상세를 말씀드립니다.',
  unlocks: [{ set: 'T06' }],
  hintTopic: '권한',
  explain: '선우강의 개발자 키는 또박이 관리자 권한이다.',
};

const C07: Break = {
  id: 'C07',
  tier: 'minor',
  type: 'contradiction',
  evidence: ['E15'],
  accept: [['VICTIM'], ['E03a'], ['E03b'], ['E05', 'E15']],
  reaction: [AI('정정합니다. 녹음된 주인님도 기준을 넘습니다.', 'shock'), AI("저는 '살아 있는 목소리'를 구분하지 못합니다.")],
  revisedText: '기준은 넘었습니다. 본인인지는 모릅니다.',
  unlocks: [],
  hintTopic: '일치율',
  explain: '녹음된 회장 목소리도 70%를 넘는다. 통과는 본인 증명이 아니다.',
};

const C08: Break = {
  id: 'C08',
  tier: 'star',
  type: 'contradiction',
  evidence: ['E06'],
  half: { E16: [S4('정장 뒷모습이요? 얼굴은 못 봤다면서요.', 'sweat'), ME('흔들린다. 서재 쪽 기록이 있으면 끝난다.')] },
  reaction: [S4('…불이요? 눈이 아파서 끄고—', 'shock'), S4('아닙니다. 정정하겠습니다.')],
  revisedText: '9시 40분 이후엔 서재에 없었습니다.',
  unlocks: [{ set: 'T07', chain: true }],
  hintTopic: '서재',
  explain: '서재 조명은 21:40에 꺼져 22:52까지 깜깜했다.',
};

const C09: Break = {
  id: 'C09',
  tier: 'star',
  type: 'contradiction',
  evidence: ['E17'],
  reaction: [
    S4('…입력이 한 번도 안 끊겼다고요.', 'sweat'),
    S4('그럼… 제가 본 건 그림자였나 봅니다.'),
    COP('이사님한테 떠넘기려던 거예요?!'),
    ME('없는 사람을 봤다. 그럼 그 시각 넌 어디 있었지.'),
  ],
  revisedText: '복도에서 누굴 봤는지는… 확실치 않습니다.',
  unlocks: [],
  hintTopic: '복도',
  explain: '선우강의 노트북 입력은 21:38~22:12 한 번도 끊기지 않았다.',
};

const C10: Break = {
  id: 'C10',
  tier: 'star',
  type: 'contradiction',
  evidence: ['E02', 'E04'],
  half: {
    E02: [S4('이 빠진 상패요? 몇 년 된 겁니다.')],
    E04: [S4('유리 조각이야 어디서든 나오죠. 컵이겠죠.')],
  },
  reaction: [
    COP('조각이 트로피 모서리에 딱 맞아요, 선배님!'),
    S4('……사고가 아니라면, 집에 있던 누군가겠죠.', 'sweat'),
    S4('전 10시 20분엔 밖이었습니다. 또박이가 들었고요.'),
    S4('못 믿으시겠으면 기계한테 물어보시죠.'),
  ],
  revisedText: '사고가 아닐 수도… 있겠습니다.',
  unlocks: [],
  hintTopic: '조각',
  explain: '트로피 모서리 조각이 시신 곁을 돈 청소기 먼지통에서 나왔다.',
};

const C11: Break = {
  id: 'C11',
  tier: 'star',
  type: 'contradiction',
  evidence: ['E05', 'E15'],
  half: {
    E05: [S4("청소기가 출발한 게 뭐요? 출발음은 '띠리링'인데."), COP("그 '생신축하' 파일… 이 집 오래 산 분은 알 텐데요.")],
    E15: [S4('생일 선물 얘기요? 그 음성, 두 달 만에 꺼졌어요.'), COP('꺼졌는지 다시 켜졌는지… 기계 기록이 있을 텐데요.')],
    VICTIM: [S4('광고 목소리라서요? 그게 녹음이란 증거는요?'), COP('녹음을 틀 수 있는 기계… 이 집에 있었나요?')],
  },
  reaction: [
    AI('대조합니다. 22:20:00, 청소기가 출발음을 냈습니다.', 'sweat'),
    AI("1초 뒤 들은 '주인님'은… 바닥에서 났습니다."),
    AI('정정합니다. 그건 청소기였습니다.', 'shock'),
    S4('…….', 'sweat'),
  ],
  revisedText: '22:20:01, 청소기 출발음을 주인님으로 잘못 판정.',
  unlocks: [{ upgrade: ['E03', 'E03a'] }],
  hintTopic: '출발음',
  explain: '22:02 출발음이 회장 녹음으로 바뀌었고 22:20에 울렸다.',
};

const C12: Break = {
  id: 'C12',
  tier: 'minor',
  type: 'contradiction',
  evidence: ['E12'],
  accept: [['E13']],
  half: { E16: [S4('뒷모습은 10시 1분이죠. 예약은 9시 58분입니다.')] },
  reaction: [S4('로비에… 계셨군요. 토요일이니까.', 'sweat'), ME('알고 있었군. 그녀의 토요일을.')],
  revisedText: '여사님은 그 시각 로비에 계셨습니다.',
  unlocks: [],
  hintTopic: '계정',
  explain: '예약이 생긴 21:58, 미숙은 쪽문 밖에 있었다(21:46~22:02).',
};

const C13: Break = {
  id: 'C13',
  tier: 'star',
  type: 'contradiction',
  evidence: ['E16'],
  requires: { broken: 'C11' },
  half: {
    requires: [S4('주방에 있었다 칩시다. 회장님 목소리랑 무슨 상관이죠?')],
    E03a: [S4('소리를 바꾼 게 저라고요? 기록엔 계정뿐입니다.', 'sweat'), ME('…본 사람. 찾아야겠군.')],
  },
  reaction: [
    S4('…하늘 씨가, 봤다고요.', 'shock'),
    S4('정리하면, 제가 설정했다 칩시다.'),
    S4('그래서요? 전 회장님 사람입니다. 동기가 없어요.', 'angry'),
    COP("선배님, 기록이 바뀌었어요! '위조'래요!"),
  ],
  revisedText: '10시 1분, 주방 태블릿 앞에 있었습니다.',
  unlocks: [{ upgrade: ['E03a', 'E03b'] }],
  hintTopic: '주방',
  explain: '22:01 주방 태블릿 앞 정장 차림. 그날 정장은 준혁뿐이었다.',
};

const C14: Break = {
  id: 'C14',
  tier: 'minor',
  type: 'contradiction',
  evidence: ['E16'],
  half: { E05: [S3('아이고, 태블릿은 자동 로그인이라 아무나 만져요.', 'sweat'), ME('누가 만졌는지. 그걸 본 사람이 필요하다.')] },
  reaction: [S3('…못 봤어요. 구두 소리만 들었어요. 주방에서.', 'sweat'), S3('착한 사람이라… 그렇게 믿고 싶었어요.')],
  revisedText: '주방에서 구두 소리를 들었어요.',
  unlocks: [],
  hintTopic: '구두',
  explain: '하늘은 22:01 주방 태블릿 앞 정장 차림을 봤다.',
};

const C15: Break = {
  id: 'C15',
  tier: 'star',
  type: 'contradiction',
  evidence: ['E17'],
  half: { E03b: [S1('정확히는… 그럼 제가 들은 쿵은 몇 시였죠?', 'sweat'), ME('그 시각을 적어 둔 기록이 있을 거다.')] },
  reaction: [S1("…제 주석이네요. 9시 46분, '쿵?'", 'shock'), S1('회장님이 뭘 떨어뜨린 줄 알았어요.'), COP('그럼 9시 46분에 이미…!')],
  revisedText: '쿵 소리는 9시 46분이었습니다.',
  unlocks: [{ flag: 'F_TOD' }],
  hintTopic: '쿵',
  explain: "선우강이 21:46 터미널에 '쿵?'이라 적었다. 22:20이 아니다.",
};

const L = (l: Line): Line => l;

export const SETS: TestimonySet[] = [
  {
    id: 'T00',
    title: '또박이의 저녁 보고',
    speakers: ['AI'],
    kind: 'tutorial',
    initial: true,
    cost: 0,
    intro: [AI('또박이입니다. 오늘 밤 기록을 보고합니다.'), COP('선배님, 기계도 틀릴 수 있어요. 아마도요.')],
    lines: [
      L({
        id: 'T00.1',
        who: 'AI',
        text: '21:00 정시 안내. 오늘 밤 강수확률 100%입니다.',
        truth: 'record',
        claimTime: '21:00',
        press: { lines: [AI('지금도 100%입니다. 우산을 챙기세요.'), ME('…증인 맞지?')] },
      }),
      L({
        id: 'T00.2',
        who: 'AI',
        text: '22:20, 명령을 받아 거실 조명을 껐습니다.',
        truth: 'record',
        claimTime: '22:20',
        press: { lines: [AI("명령은 '불 꺼. 오늘은 여기까지.' 주인님 말버릇입니다."), COP('광고에 나오던 그거네요!')] },
      }),
      L({
        id: 'T00.3',
        who: 'AI',
        text: '그 뒤로 거실엔 아무도 없었습니다. 움직임이 없었으니까요.',
        truth: 'inference',
        press: { lines: [AI('제 동작 감지 기준으로는 그렇습니다.'), ME('기준이라. 한번 따져 볼까.')] },
        breaks: [C01],
      }),
      L({
        id: 'T00.4',
        who: 'AI',
        text: "22:39, 등록 사용자의 '불 켜'. 그리고 비명입니다.",
        truth: 'record',
        claimTime: '22:39',
        press: { lines: [AI('비명은 명령이 아니라서 처리하지 않았습니다.'), ME('…그래, 그렇겠지.')] },
      }),
    ],
    outro: [AI('보고를 마칩니다. 참고로 내일은 맑습니다.'), COP('다음부턴 틀리면 제 인내심이 깎여요, 선배님.')],
  },
  {
    id: 'T01',
    title: '정확히는, 손님방',
    speakers: ['S1'],
    kind: 'first',
    initial: true,
    cost: 1,
    intro: [S1('선우강. 또박이 설계자. 정확히는 공동창업자.'), S1('짧게 묻죠. 지금 머리가 복잡해서.')],
    lines: [
      L({
        id: 'T01.1',
        who: 'S1',
        text: '저녁 뒤론 손님방에 있었어요. 비 때문에 자고 가기로.',
        truth: 'true',
        press: { lines: [S1('문 잠그고 일했어요. 습관입니다.'), COP('그래서 손님방이 잠겨 있었군요.')] },
      }),
      L({
        id: 'T01.2',
        who: 'S1',
        text: '오늘 밤 이 집 시스템엔 손가락 하나 안 댔습니다.',
        truth: 'lie',
        press: { lines: [S1('정확히는, 키보드에만 댔죠. 농담입니다.'), ME('농담이 아니라면?')] },
        breaks: [C02],
      }),
      L({
        id: 'T01.3',
        who: 'S1',
        text: "10시 조금 넘어 비서님 '다녀오겠습니다' 소리 들었어요.",
        truth: 'true',
        claimTime: '22:03',
        press: { lines: [S1('회장님 대답은… 글쎄요. 이어폰을 끼고 있어서.')] },
      }),
      L({
        id: 'T01.4',
        who: 'S1',
        text: "10시 20분엔 '불 꺼' 소리. 광고 그 목소리였죠.",
        truth: 'true',
        claimTime: '22:20',
        press: {
          lines: [S1('근데 소리가 낮았어요. 정확히는, 바닥 높이.'), ME('바닥 높이라고?')],
          question: { id: 'Q06', text: '10시 20분의 목소리는 왜 바닥에서 났나?', resolvedBy: ['C11'], answer: '바닥을 도는 청소기의 출발음이었다.' },
        },
        redirect: { cards: R_VOICE, say: [S1('정확히는, 그건 제 말이 맞다는 증거죠.'), S1('따질 상대는 제가 아니라 그 기록을 믿는 쪽이에요.')] },
      }),
    ],
    outro: [],
  },
  {
    id: 'T02',
    title: '방 안의 작가',
    speakers: ['S2'],
    kind: 'first',
    initial: true,
    cost: 1,
    intro: [S2('백하늘. 웹소설 써요. 아빤 독자가 아니었고요.'), S2('…라고 하늘은 담담하게 말했다.')],
    lines: [
      L({
        id: 'T02.1',
        who: 'S2',
        text: '9시 반에 아빠랑 싸웠어요. 유언장 때문에.',
        truth: 'true',
        claimTime: '21:30',
        press: { lines: [S2("재단에 다 준대요. 저한텐 '알아서 살아라'."), COP('(기록하겠습니다…)')] },
      }),
      L({
        id: 'T02.2',
        who: 'S2',
        text: '9시 35분부터 방에서 한 발짝도 안 나갔어요.',
        truth: 'lie',
        claimTime: '21:35',
        press: { lines: [S2('이어폰 끼고 원고 썼어요. 마감이라.'), ME('마감은 탐정도 무섭다.')] },
        breaks: [C04],
      }),
      L({
        id: 'T02.3',
        who: 'S2',
        text: "10시 20분엔 방에서 '불 꺼' 소리를 들었어요.",
        truth: 'true',
        claimTime: '22:20',
        press: { lines: [S2('이상하게 낮게 깔렸어요. 바닥에서 올라오듯.'), S2('…라고 하늘은 복선을 깔았다.')] },
        redirect: { cards: R_VOICE, say: [S2('그거 제 복선 회수잖아요. 반박이 아니라.'), S2('반전은 그 목소리를 믿는 사람 앞에서 터뜨리세요.')] },
      }),
      L({
        id: 'T02.4',
        who: 'S2',
        text: '아빠를 죽일 이유요? 많죠. 소설에서만요.',
        truth: 'true',
        press: { lines: [S2('농담이에요. 웃을 기분은 아니지만.')] },
      }),
    ],
    outro: [],
  },
  {
    id: 'T03',
    title: '10년 차의 밤',
    speakers: ['S3'],
    kind: 'first',
    initial: true,
    cost: 1,
    intro: [S3('방미숙이에요. 이 집 10년. 아이고, 참말로.')],
    lines: [
      L({
        id: 'T03.1',
        who: 'S3',
        text: '저녁 치우고 9시 반에 제 방에 들어갔어요.',
        truth: 'true',
        claimTime: '21:30',
        press: { lines: [S3('방은 다용도실 뒤예요. 쪽문 바로 옆.'), ME('쪽문 옆이라.')] },
      }),
      L({
        id: 'T03.2',
        who: 'S3',
        text: '눕자마자 잤어요. 아침까지 쭉이요.',
        truth: 'lie',
        press: { lines: [S3('내가 원래 잠이 많아요. 눕자마자 꿀잠.'), COP('…근데 어디서 치킨 냄새 안 나요?')] },
        breaks: [C03],
      }),
      L({
        id: 'T03.3',
        who: 'S3',
        text: '자다 깼는데, 10시 20분쯤 청소기가 돌더라고요.',
        truth: 'true',
        claimTime: '22:20',
        press: {
          lines: [S3('회장님은 밤 청소 질색하세요. 시끄럽다고.'), S3('그 청소기엔 사연도 있고… 아이고, 아니에요.'), ME('사연이라. 그럼 누가 돌렸지?')],
        },
        redirect: { cards: ['E13', 'E12'], say: [S3('아이고, 이건 깬 얘기고요. 잔 얘기는 아까 했잖아요!', 'sweat'), ME('…잔 얘기. 앞에서 한 그 말이 수상하다.')] },
      }),
      L({
        id: 'T03.4',
        who: 'S3',
        text: '회장님이 저 내보낸대요. 집 판다고. 10년인데.',
        truth: 'true',
        press: { lines: [S3('통지서는 냉장고에 붙여 놨어요. 매일 보라고.'), COP('…그건 좀 너무하네요.')] },
      }),
    ],
    outro: [],
  },
  {
    id: 'T04',
    title: '발표 전야',
    speakers: ['S4'],
    kind: 'first',
    initial: true,
    cost: 1,
    intro: [S4('회장님 수행비서 표준혁입니다. 확인해 보겠습니다.'), S4('…아니, 무엇이든 여쭤보십시오.')],
    lines: [
      L({
        id: 'T04.1',
        who: 'S4',
        text: '저녁 뒤 8시 40분부터 서재에서 발표 자료를 뽑았습니다.',
        truth: 'true',
        claimTime: '20:40',
        press: { lines: [S4('내일 10시 은퇴 발표. 원고만 열두 번 고쳤습니다.'), S4('틀린 인쇄본은 전부 파쇄기로 보냈고요.')] },
      }),
      L({
        id: 'T04.2',
        who: 'S4',
        text: '9시 40분부터 10시 5분까지도 쭉 서재였습니다.',
        truth: 'lie',
        claimTime: '21:40',
        press: { lines: [S4('확인해 보겠습니다. …네, 서재 맞습니다.'), ME('확인하는 척이 빠르다.')] },
        breaks: [C08],
      }),
      L({
        id: 'T04.3',
        who: 'S4',
        text: '10시 5분에 편의점에 다녀왔습니다. 영수증 22시 12분.',
        truth: 'true',
        claimTime: '22:05',
        press: { lines: [S4('우산이랑 숙취해소제. 회장님 드시라고요.')] },
      }),
      L({
        id: 'T04.4',
        who: 'S4',
        text: '10시 38분 돌아와 불을 켜니… 쓰러져 계셨습니다.',
        truth: 'true',
        claimTime: '22:38',
        press: { lines: [S4('바로 112에 걸었습니다. 손이 떨려서 두 번.')] },
      }),
      L({
        id: 'T04.5',
        who: 'S4',
        text: '또박이가 10시 20분에 회장님 목소리를 들었답니다.',
        truth: 'true',
        claimTime: '22:20',
        press: { lines: [S4('전 그때 밖이었고요. 기계는 거짓말 안 하죠.')] },
        redirect: { cards: R_VOICE, say: [S4('목소리를 따지시려면 또박이 앞에서 하시죠.'), S4('들은 건 제가 아니라 기계니까요.')] },
      }),
    ],
    outro: [],
  },
  {
    id: 'T05',
    title: '오늘 밤의 기록',
    speakers: ['AI'],
    kind: 'ai',
    initial: true,
    cost: 1,
    intro: [AI('게스트 권한 기록입니다. 요약해 드립니다.'), COP('기계가 요약을요? 저보다 낫네…')],
    lines: [
      L({
        id: 'T05.1',
        who: 'AI',
        text: '21:30, 거실 대화. 주인님과 등록 사용자 한 분.',
        truth: 'record',
        claimTime: '21:30',
        press: {
          lines: [AI("내용은 저장하지 않습니다. 목소리 크기 '큼'."), ME('다툼이다. 상대는?')],
          question: { id: 'Q01', text: '9시 반, 회장과 큰 소리로 다툰 사람은?', resolvedBy: ['C04'], answer: '하늘. 유언장 문제로 다퉜다고 직접 말했다.' },
        },
      }),
      L({
        id: 'T05.2',
        who: 'AI',
        text: "21:38, 외부 기기 'KANG-NOTE' 접속. 데이터 삭제 명령.",
        truth: 'record',
        claimTime: '21:38',
        press: { lines: [AI('무엇이 지워졌는지는 저도 모릅니다.'), COP('KANG… 선우강 이사님 노트북?!')], gives: 'E14' },
      }),
      L({
        id: 'T05.3',
        who: 'AI',
        text: '21:41부터 15분 기록 없음. 네트워크 장애로 추정합니다.',
        truth: 'inference',
        claimTime: '21:41',
        press: {
          lines: [AI('인터넷이 끊기면 저는 아무것도 못 적습니다.'), AI('상세 원인은 관리자 기록에 있습니다.'), AI('참고로 공유기는 다용도실에 있습니다. 깜빡깜빡.')],
          reveals: 'T05.6',
          question: { id: 'Q02', text: '21:41부터 15분, 왜 기록이 비었나?', resolvedBy: ['C05'] },
        },
        breaks: [C05],
      }),
      L({
        id: 'T05.4',
        who: 'AI',
        text: "22:03, 등록 사용자 발화. '회장님, 편의점 다녀오겠습니다!'",
        truth: 'record',
        claimTime: '22:03',
        press: {
          lines: [AI('대답은 기록되지 않았습니다.'), ME('…대답이 없었다고?')],
          question: { id: 'Q03', text: '10시 3분 인사에, 회장은 왜 대답이 없었나?', resolvedBy: ['C13'], answer: '회장은 그때 이미 쓰러져 있었다.' },
        },
      }),
      L({
        id: 'T05.5',
        who: 'AI',
        text: '22:20, 청소기 출발 확인. 22:24 멈춤.',
        truth: 'record',
        claimTime: '22:20',
        press: {
          lines: [AI('청소기와 저는 친구입니다. 대화는 안 되지만요.'), AI("멈춘 사유는 바퀴 걸림. 먼지통엔 '큰 이물질' 경고."), COP('불 꺼지자마자 출발했네요? 먼지통도 봐야겠어요.')],
          flag: 'F_DUST',
          question: { id: 'Q04', text: '밤 청소를 싫어하는 집에서 청소기는 왜 22:20에?', resolvedBy: ['C11'] },
        },
        redirect: { cards: R_VOICE, say: [AI('청소기 출발은 사실입니다. 기록은 바뀌지 않습니다.'), AI('제 판정이 틀렸다면, 판정한 줄에서 말씀해 주세요.')] },
      }),
      L({
        id: 'T05.6',
        who: 'AI',
        text: '공백의 상세는 관리자 기록입니다. 권한이 없습니다.',
        truth: 'refusal',
        hidden: true,
        press: { lines: [AI('죄송해요, 잘 모르겠어요.', 'angry'), AI('…가 아니라, 말할 수 없습니다.')] },
        redirect: {
          cards: ['E14'],
          say: [AI("그 기기의 '키'라면 열립니다.", 'angry'), AI('키는 기기 주인이 갖고 있습니다.'), COP('KANG… 이사님한테 받아 와야겠네요.')],
        },
        breaks: [C06],
      }),
    ],
    outro: [],
  },
  {
    id: 'T06',
    title: '관리자 전용',
    speakers: ['AI'],
    kind: 'ai',
    initial: false,
    cost: 1,
    unlock: { broken: 'C06' },
    intro: [AI('관리자 모드입니다. 말투가 딱딱해집니다.'), AI('…원래도 딱딱했습니다.')],
    lines: [
      L({
        id: 'T06.1',
        who: 'AI',
        text: '21:41:05, 마이크 끔. 본체 윗면 버튼, 손으로.',
        truth: 'record',
        claimTime: '21:41',
        press: { lines: [AI('누른 손은 모릅니다. 저는 눈이 없습니다.'), ME('그 시각, 거실에 누군가 있었다.')] },
      }),
      L({
        id: 'T06.2',
        who: 'AI',
        text: '21:56:40, 마이크 켬. 같은 버튼입니다.',
        truth: 'record',
        claimTime: '21:56',
        press: {
          lines: [AI('끈 분이 다시 켰을 가능성이 높습니다. 추정입니다.'), ME('15분 뒤 다시 켰다. 뭘 들려주려고?')],
          question: { id: 'Q05', text: '꺼진 마이크를 15분 뒤 다시 켠 이유는?', resolvedBy: ['C11'], answer: '22:20 가짜 목소리를 또박이에게 들려주려고.' },
        },
      }),
      L({
        id: 'T06.3',
        who: 'AI',
        text: '22:20:01 판정. 일치율 71%. 주인님 평소엔 96%.',
        truth: 'record',
        claimTime: '22:20',
        press: { lines: [AI('기준은 70%. 1% 차이로 통과했습니다.'), COP('아슬아슬하네요?')] },
        redirect: { cards: R_VOICE, say: [AI('수치는 사실입니다. 바꿀 수 없습니다.'), AI('해석이라면, 다음 줄에서 하겠습니다.')] },
      }),
      L({
        id: 'T06.4',
        who: 'AI',
        text: '71%라도 기준을 넘었으니 주인님 본인입니다.',
        truth: 'inference',
        press: { lines: [AI('저는 기준을 믿습니다. 기준이 저니까요.')] },
        breaks: [C07],
      }),
      L({
        id: 'T06.5',
        who: 'AI',
        text: '예약 알림 1건. 내일 07:00. 21:25 주인님 등록.',
        truth: 'record',
        press: {
          lines: [AI('내용은 주인님께만 말씀드립니다.'), AI("주인님 부재가 '확정'되면, 남은 분께 전합니다."), ME('…사건을 제대로 닫아야 들을 수 있는 말이군.')],
          flag: 'F_ALARM',
        },
      }),
    ],
    outro: [AI('관리자 모드 종료. 말투가 다시 부드러워집니다~')],
  },
  {
    id: 'T07',
    title: '불 꺼진 서재',
    speakers: ['S4'],
    kind: 'second',
    initial: false,
    cost: 0,
    unlock: { broken: 'C08' },
    intro: [S4('…정정하겠습니다. 서재는 9시 40분까지.', 'sweat'), S4('정리하면, 그 뒤가 궁금하신 거겠죠.')],
    lines: [
      L({
        id: 'T07.1',
        who: 'S4',
        text: '9시 40분에 불 끄고 나왔습니다. 머리 좀 식히려고.',
        truth: 'true',
        claimTime: '21:40',
        press: {
          lines: [S4('어디서 식혔는지가 그렇게 중요합니까.'), ME('중요하다. 그 25분이 전부다.')],
          question: { id: 'Q08', text: '서재 불을 끄고 25분, 준혁은 어디 있었나?', resolvedBy: ['C13'] },
        },
      }),
      L({
        id: 'T07.2',
        who: 'S4',
        text: '9시 반엔 서재까지 하늘 씨 고함이 들렸습니다.',
        truth: 'true',
        claimTime: '21:30',
        press: { lines: [S4('유언장 얘기였죠. 정리하면, 동기는 그쪽이 큽니다.'), ME('남의 동기는 술술 정리하는군.')] },
      }),
      L({
        id: 'T07.3',
        who: 'S4',
        text: '9시 50분쯤 복도에서 선우강 이사님을 봤습니다.',
        truth: 'lie',
        claimTime: '21:50',
        press: {
          lines: [S4('회색 후드티. 손님방 쪽으로 급히 들어가시더군요.'), COP('이사님은 방에서 안 나왔다던데요…?'), ME('둘 중 하나는 거짓말이다. 기록이 필요하다.')],
        },
        breaks: [C09],
      }),
      L({
        id: 'T07.4',
        who: 'S4',
        text: '회장님은 혼자 넘어지신 겁니다. 사고예요, 분명히.',
        truth: 'lie',
        press: { lines: [S4('불 꺼진 거실, 청소기, 대리석 모서리. 정리하면 그렇죠.'), COP('제 메모랑 똑같네요… 그쵸?')] },
        breaks: [C10],
      }),
      L({
        id: 'T07.5',
        who: 'S4',
        text: '회장님 밑에서 7년. 아버지 연구소가 망한 뒤부터요.',
        truth: 'true',
        press: {
          lines: [S4('아버지 성함요? 표명환. 음향 기술자셨죠.'), S4('그게 사건과 무슨 상관입니까.')],
          question: {
            id: 'Q07',
            text: '음향 기술자였던 그의 아버지. 회장과는 무슨 사이였나?',
            resolvedBy: ['E09'],
            answer: "1999년 특허. 발명자 '…명환', 출원인은 회장.",
          },
        },
        redirect: { cards: ['E09'], say: [S4('…발명자 성이 잘렸군요. 흔한 이름입니다.', 'sweat'), ME('흔한 이름에 땀이라. 이건 지목 때 꺼낼 패다.')] },
      }),
    ],
    outro: [],
  },
  {
    id: 'T08',
    title: '치킨은 죄가 없다',
    speakers: ['S3'],
    kind: 'second',
    initial: false,
    cost: 1,
    unlock: { broken: 'C03' },
    intro: [S3('다 털렸으니 편하게 말할게요.'), S3('치킨은 다 먹었어요. 증거 인멸은 아니고.')],
    lines: [
      L({
        id: 'T08.1',
        who: 'S3',
        text: '10시 2분, 쪽문으로 들어왔어요. 치킨 숨겨서.',
        truth: 'true',
        claimTime: '22:02',
        press: { lines: [S3('다용도실 뒤로 해서 제 방으로 바로요.')] },
      }),
      L({
        id: 'T08.2',
        who: 'S3',
        text: "그때 주방에서 '설정이 저장되었습니다' 소리가 났어요.",
        truth: 'true',
        claimTime: '22:02',
        press: { lines: [S3('태블릿 소리예요. 매일 들으니 알지.'), ME('10시 2분, 누가 태블릿을 만졌다.')] },
      }),
      L({
        id: 'T08.3',
        who: 'S3',
        text: '비서님은 그때 현관에서 신발 신고 있었어요.',
        truth: 'lie',
        press: { lines: [S3('그 양반 착해요. 내 치킨 비밀도 지켜 줬고.'), ME('…알고 있었다고?')] },
        breaks: [C14],
      }),
      L({
        id: 'T08.4',
        who: 'S3',
        text: '트로피요? 매일 닦는데, 오늘은 반 뼘 옆에 있었어요.',
        truth: 'true',
        press: { lines: [S3('다들 나왔을 때 봤어요. 10년 눈썰미예요.'), COP('누가 옮겼다는 거네요.')] },
      }),
    ],
    outro: [],
  },
  {
    id: 'T09',
    title: '쿵은 언제였나',
    speakers: ['S1', 'S2'],
    kind: 'confront',
    initial: false,
    cost: 0,
    unlock: { all: [{ broken: 'C05' }, { broken: 'C02' }, { broken: 'C04' }] },
    intro: [COP('두 분 얘기가 엇갈려요. 같이 들어 보죠.'), S1('정확히는, 엇갈린 게 아니라 저쪽이 틀린 거죠.'), S2('…라고 아저씨는 우겼다.')],
    lines: [
      L({
        id: 'T09.1',
        who: 'S1',
        text: '전 9시 38분부터 손님방에서 데이터만 지웠어요.',
        truth: 'true',
        claimTime: '21:38',
        press: { lines: [S1('10시 12분까지 키보드 앞. 화장실도 안 갔어요.'), S2('그걸 누가 믿어요?')] },
      }),
      L({
        id: 'T09.2',
        who: 'S2',
        text: '전 옥상에서 통화 중이었어요. 쿵? 못 들었어요.',
        truth: 'true',
        press: { lines: [S2('옥상은 빗소리뿐이었어요. 천창도 닫혀 있었고.')] },
      }),
      L({
        id: 'T09.3',
        who: 'S1',
        text: '쿵 소리는 10시 20분쯤. 불 꺼지고 바로였어요.',
        truth: 'mistaken',
        claimTime: '22:20',
        press: { lines: [S1('정확히는… 기억이 좀 섞였을 수도.'), ME('기억 말고 기록이 필요하다.')] },
        breaks: [C15],
      }),
      L({
        id: 'T09.4',
        who: 'S2',
        text: '10시 1분, 내려오다 주방에서 정장 뒷모습을 봤어요.',
        truth: 'true',
        claimTime: '22:01',
        press: { lines: [S2('그날 밤 정장 입은 사람은… 한 명뿐이죠.'), S1('정확히는, 나는 후드티.')] },
      }),
      L({
        id: 'T09.5',
        who: 'S1',
        text: '10시 20분 목소리는 바닥에서 났어요. 스피커 소리.',
        truth: 'true',
        press: { lines: [S1('압축 음원 특유의 쨍한 소리. 제 귀는 정확해요.')] },
        redirect: { cards: R_VOICE, say: [S1('정확히는, 제 귀가 맞았다는 증거네요.'), S2('반박할 상대가 틀렸어요, 탐정님.')] },
      }),
    ],
    outro: [S2('…장면 전환. 진짜 범인은 다른 곳에.'), S1('정확히는, 다른 방에.')],
  },
  {
    id: 'T10',
    title: '또박이는 들었다',
    speakers: ['S4', 'AI'],
    kind: 'confront',
    initial: false,
    cost: 0,
    unlock: { all: [{ broken: 'C05' }, { broken: 'C10' }] },
    intro: [S4('좋습니다. 기계는 거짓말 안 하죠.'), S4('또박이, 10시 20분에 들은 걸 말해 줘.'), AI('네. 또박또박 말씀드리겠습니다.')],
    lines: [
      L({
        id: 'T10.1',
        who: 'S4',
        text: '전 10시 5분에 나갔습니다. 월패드에도 남았죠.',
        truth: 'true',
        claimTime: '22:05',
        press: { lines: [S4('편의점 영수증 22시 12분. 확인하시죠.'), COP('확인했어요. 진짜예요.')] },
      }),
      L({
        id: 'T10.2',
        who: 'AI',
        text: "22:20:01, 주인님 음성 명령. '불 꺼. 오늘은 여기까지.'",
        truth: 'record',
        forged: true,
        claimTime: '22:20',
        press: { lines: [AI('주인님 목소리로 판정했습니다. 기준을 넘었습니다.'), S4('들으셨죠? 회장님입니다.')] },
        breaks: [C11],
      }),
      L({
        id: 'T10.3',
        who: 'S4',
        text: '청소기 예약요? 집사 계정이면 미숙 여사님이겠죠.',
        truth: 'lie',
        press: { lines: [S4('공용 계정은 저랑 여사님만 씁니다. 전 나갔고요.'), ME('둘 중 하나란 건 인정하는군.')] },
        breaks: [C12],
      }),
      L({
        id: 'T10.4',
        who: 'S4',
        text: '나가기 전엔 복도에서 통화했습니다. 주방엔 안 갔고요.',
        truth: 'lie',
        press: {
          lines: [S4('통화 상대요? 거래처입니다. 이름은… 기억이.'), S4('복도는 깜깜했습니다. 옥상 계단 쪽도요.'), ME('확인 버릇이 사라졌다. 그리고… 옥상 계단?')],
        },
        redirect: {
          cards: ['E05', 'E12'],
          say: [S4('기록은 계정과 문 얘기죠. 사람 얘기가 아니라.'), S4('제가 주방에 있는 걸 본 사람이라도 있습니까?'), ME('…본 사람. 찾아야겠군.')],
        },
        breaks: [C13],
      }),
    ],
    outro: [S4('…판단은 강력팀이 하겠죠.'), COP('선배님, 이제 지목하셔도 돼요.')],
  },
];

// ─────────────────────────────── 최종 지목 정답 (진상) ───────────────────────────────

export const SOLUTION: Solution = {
  culprit: 'S4',
  accept: {
    means: ['E02', 'E04'],
    opportunity: ['E03b'],
    motive: ['E09'],
  },
  hiddenEnding: { all: [{ flag: 'F_ALARM' }, { broken: 'C02' }, { broken: 'C03' }, { broken: 'C04' }] },
  accuseWarn: [
    {
      when: { hasEvidence: 'E03a' },
      lines: [COP('선배님, 청소기 소리를 바꾼 사람은 아직 못 밝혔어요.', 'sweat'), COP('강력팀은 기록부터 볼 텐데… 이대로 넘길까요?')],
    },
    {
      when: { not: { hasEvidence: 'E03b' } },
      lines: [COP('선배님, 10시 20분 회장님 목소리 기록은 아직 그대로예요.', 'sweat'), COP('강력팀은 기록부터 볼 텐데… 이대로 넘길까요?')],
    },
  ],
  decoys: {
    means: ['E01', 'E14'],
    opportunity: ['E03', 'E03a', 'E05', 'E06', 'E12', 'E17'],
    motive: ['E07', 'E08', 'E10'],
  },
};

// ─────────────────────────────── 사건 파일 ───────────────────────────────

export const CASE: CaseFile = {
  id: 'witness-01',
  title: '스마트홈 살인사건 — 목격자는 AI 스피커',
  shortTitle: '목격자는 AI',
  names: NAMES,
  intro: [
    { art: 'tower', lines: [NARR('토요일 밤 10시 39분. 한강엔 폭우.'), NARR('물비늘타워 41층에서 비명이 울렸다.')] },
    { art: 'stair', lines: [ME('난 40층 주민. 전직 강력계 형사, 지금은 동네 탐정.'), ME('계단을 뛰어 올라갔다.')] },
    { art: 'cop-window', lines: [COP('충성! …아니, 선배님? 실습 때 한결이요!'), COP('강변도로가 잠겨서 강력팀은 새벽 1시에 온대요.')] },
    { art: 'ad-frame', lines: [NARR('도진랩 회장 백도진, 62세. 거실에서 숨진 채 발견됐다.'), NARR("광고 유행어는 '또박아, 불 꺼. 오늘은 여기까지.'")] },
    { art: 'cop-ddobagi', lines: [COP('다들 사고래요. 불 끄고 걷다 청소기에 걸렸다고.'), COP('근데 이 집, 기계가 다 듣고 있었대요.')] },
    { art: 'suspects', lines: [NARR('집 안엔 넷. 공동창업자, 딸, 가사관리인, 수행비서.'), NARR('그리고 목격자가 한 대.')] },
    { art: 'ddobagi', lines: [AI('안녕하세요, 또박이입니다. 무엇이든 또박또박.'), ME('…증인이 스피커라니.')] },
    { art: 'clock', lines: [COP('공식적으론 안 되는데요. 강력팀 올 때까지만요.'), ME('22시 50분. 두 시간이면 충분하다.')] },
  ],
  rules: [
    '강력팀 도착까지 행동 13번. 처음 가는 장소, 처음 듣는 증언에 한 번씩 든다. 행동이 0이 되면 사이렌 — 새로운 곳은 끝, 이미 연 곳은 다시 볼 수 있다.',
    '증언의 모순에 증거를 내밀어라. 틀리면 신뢰도가 깎인다.',
    '결정적 모순 3개를 깨면 범인을 지목할 수 있다. 범인과 증거 3개(수단·기회·동기)를 고른다.',
  ],
  cutIns: { press: '다시 말해 봐!', present: '증거 나간다!', break: '앞뒤가 안 맞아!' },
  profiles: PROFILES,
  evidence: EVIDENCE,
  locations: LOCATIONS,
  sets: SETS,
  solution: SOLUTION,
  hintRoute: ['C05', 'C08', 'C10', 'C03', 'C04', 'C11', 'C13'],
  wrongReactions: {
    S1: ['정확히는, 그건 아무 상관 없습니다.', '해상도가 낮은 추리네요.', '버그 리포트는 다른 데 내세요.'],
    S2: ['개연성 0점이에요.', '그 복선, 회수 안 돼요.', '…라고 탐정은 헛다리를 짚었다.'],
    S3: ['아이고, 그걸 왜 나한테 들이밀어요.', '그거 내가 어제 닦은 거예요!', '배고파서 그래요? 뭐 좀 줘요?'],
    S4: ['확인해 보았습니다. 무관합니다.', '일정에 없는 증거군요.', '수고 많으십니다. 다음 건 보시죠.'],
    AI: ['해당 물건은 기록과 관련이 없습니다. 내일은 맑음.', '장보기 목록에 추가할까요?', '이해하지 못했어요. 다시 내밀어 주세요.'],
  },
  copTrustLines: {
    5: '선배님 믿어요!',
    4: '기록하겠습니다…!',
    3: '선배님… 괜찮으시죠?',
    2: '저 보고서 쓰기 무서워요…',
    1: '한 번만 더 틀리면 저…',
  },
  endings: {
    perfect: {
      title: '진짜로, 오늘은 여기까지',
      lines: [
        S4("회장님은 '내일 얘기하자'고 하셨습니다."),
        S4("'오늘은 여기까지.' 아버지 얘기를, 그 한마디로."),
        S4('…그래서 저도 거기서 끝냈습니다.', 'break'),
        NARR('그는 넥타이를 풀었다. 처음 보는 모습이었다.'),
        NARR('새벽 1시. 강력팀이 도착했다.'),
        COP('선배님, 보고서 제 이름으로 올려도 돼요?'),
        ME('…강력팀엔 내가 설명한다고 했지.'),
        AI('수사 종료를 확인했습니다. 참고로 내일은 맑습니다.'),
      ],
    },
    hidden: {
      title: '마지막 알람',
      lines: [
        AI('주인님 부재를 확인했습니다. 알림을 전해도 될까요.'),
        AI('21시 25분, 주인님이 남기신 내일 7시 알림입니다.'),
        AI("'준혁이 아버지 특허 건. 변호사 전에, 준혁이한테 먼저.'"),
        AI("'미안하다고 할 것.' 이상입니다."),
        S4('……내일 얘기하자는 게.'),
        S4('그 얘기였습니까.'),
        NARR('아무도 대답하지 않았다. 빗소리만 남았다.'),
        AI('07:00 알림은 취소할까요?'),
        ME('…아니. 울리게 둬.'),
      ],
    },
    short: {
      title: '심증만 가득',
      lines: [
        ME('범인은 당신이다.'),
        S4('확인해 보았습니다. 증거가 모자라는군요.'),
        NARR('새벽 1시. 강력팀과 함께 변호사도 왔다.'),
        NARR('변호사는 웃으며 그를 데려갔다.'),
        COP('선배님… 이대로 끝이에요?'),
        ME('아직 놓친 게 있다. 수첩 어딘가에.'),
      ],
    },
    'wrong-S1': {
      title: '정확히는, 오인입니다',
      lines: [
        S1('정확히는, 전 데이터를 지웠지 사람을 지우진 않았어요.'),
        NARR('다음 날 뉴스. 「또박이, 몰래 집안 소리 학습」.'),
        NARR('매각은 무산됐다. 진짜 범인은 아직 그 집에 있다.'),
        AI('참고로, 저는 이제 아무것도 배우지 않습니다.'),
      ],
    },
    'wrong-S2': {
      title: '장면 전환 실패',
      lines: [
        S2('…라고, 탐정은 틀렸다.'),
        NARR('그녀의 소설 『우리 아빠는 스마트하지 않다』는 대박이 났다.'),
        NARR("띠지 문구. '진짜 범인은 아직 이 집에.'"),
        COP('선배님, 저 그 책 샀어요…'),
      ],
    },
    'wrong-S3': {
      title: '치킨은 죄가 없다',
      lines: [
        S3('아이고, 내가 한 거라곤 치킨 시킨 것뿐이에요!'),
        NARR('영수증이 공개됐다. 21:52, 로비 전달.'),
        NARR('그녀는 그날로 풀려났다. 단골 치킨집은 쿠폰을 보냈다.'),
        ME('범인은… 아직 그 집에 있다.'),
      ],
    },
    timeout: {
      title: '사이렌이 먼저 왔다',
      lines: [
        NARR('새벽 1시. 사이렌이 먼저 왔다.'),
        NARR('강력팀은 기록부터 봤다. 22:20, 회장 본인 음성.'),
        NARR("사건은 '어둠 속 낙상 사고'로 정리됐다."),
        AI('수사 종료를 확인했습니다. 불을 끌까요?'),
        ME('…끄지 마.'),
      ],
    },
    excluded: {
      title: '수첩 압수',
      lines: [
        COP('선배님… 죄송해요. 더는 못 봐 드려요.'),
        NARR('수첩을 압수당했다. 현장에서 밀려났다.'),
        AI('출입 기록. 탐정님, 퇴장.'),
        ME('…한 번만 더. 심문 전으로.'),
      ],
    },
  },
  easterEgg: [COP('선배님… 스피커를 체포할 순 없습니다.'), AI('체포 시 전원을 뽑으시겠습니까? 참고로 저는 증인입니다.')],
  verdict: {
    call: ME('범인은— {name}, 당신이다.'),
    means: { ok: [S4('…닦았는데.')], ng: [S4('그게 흉기라고요? 확인해 보았습니다. 무관합니다.')] },
    opportunity: {
      ok: [S4('기계가… 저를 팔았군요.')],
      ng: [S4('그건 제 알리바이를 증명할 뿐입니다.')],
      byCard: {
        E03: [S4('보세요. 회장님 목소리라잖아요.')],
        E03a: [S4('청소기 소리였다 칩시다. 바꾼 게 저란 증거는요?')],
        E06: [S4('서재에 없었다는 것뿐입니다. 회장님은 10시 20분에 살아 계셨죠.')],
        E05: [S4('예약은 공용 계정입니다. 회장님 목소리는 그 뒤에 들렸고요.')],
        E11: [S4('그 시각 전 집에 있었죠. 회장님도 살아 계셨고요.')],
        E12: [S4('그 시각 전 집에 있었죠. 회장님도 살아 계셨고요.')],
      },
    },
    motive: { ok: [S4('아버지 이름을… 거기서 보셨군요.')], ng: [S4('그건 제 이야기가 아닙니다.')] },
  },
  titles: {
    S: '한강뷰 명탐정',
    A: '로그를 읽는 사람',
    B: '아깝다, 반 박자',
    short: '심증만 가득',
    wrong: '스피커도 당황한 추리',
    timeout: '사이렌이 먼저 왔다',
    excluded: '수첩 압수',
  },
  copy: {
    half: ME('흔들린다… 그런데 딱 맞진 않는다.'),
    already: ME('이미 깨진 얘기다.'),
    wrongMonologue: ME('…헛다리였다.'),
    hintLead: '수첩을 펼쳐 지금까지를 정리했다.',
    hintBreakable: ['{who}의 「{title}」.', "'{topic}' 얘기가 걸린다. 가진 걸로 충분하다."],
    hintPlace: '{place}{을를} 아직 덜 본 것 같다.',
    hintRevisit: '{place}에 다시 가 볼 이유가 생겼다.',
    hintAsk: '{who}에게 아직 묻지 않은 게 있다.',
    hintPress: '{who}의 말을 더 캐물어 볼 만하다.',
    hintDone: '이제 지목해도 된다. 수단·기회·동기, 하나씩.',
  },
};
